FROM python:3.10

# Définir le dossier de travail
WORKDIR /app

# Copier requirements.txt
COPY requirements.txt .

# Installer les dépendances
RUN pip install --no-cache-dir -r requirements.txt

# Copier le reste du code
COPY . .

# ⚡ Lancer l'entraînement pour générer model.pkl et encoder.pkl
RUN python model_pipeline.py

# Exposer le port FastAPI
EXPOSE 8000

# Lancer le serveur
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
